---
- name: Restart Docker
  systemd:
    name: docker
    state: restarted
  become: yes

- name: Restart MariaDB
  systemd:
    name: mariadb
    state: restarted

- name: Restart Apache
  systemd:
    name: httpd
    state: restarted

- name: Restart PHP-FPM
  systemd:
    name: php-fpm
    state: restarted

- name: Restart Git Auto-Sync
  systemd:
    name: git-autosync
    state: restarted
