---
# Handlers - Descomente/adicionem quando necess√°rio
# Exemplo: usar quando modificar /etc/mkinitcpio.conf

# - name: Regenerate Initramfs
#   command: mkinitcpio -P
#   become: yes
#   when: ansible_facts['os_family'] == 'Archlinux'

- name: Restart SDDM
  systemd:
    name: sddm
    state: restarted
  become: yes
