---
project_name: ArchDev
target_user: "{{ ansible_facts['env']['SUDO_USER'] | default(ansible_facts['user_id']) }}" 
target_home: "/home/{{ target_user }}"

# --- Official Repositories (Pacman) ---

packages_hyprland:
  - hyprland
  - xdg-desktop-portal-hyprland
  - xdg-desktop-portal-gtk
  - polkit-kde-agent
  - qt5-wayland
  - qt6-wayland
  - kvantum
  - kvantum-qt5
  - hyprlock
  - hypridle
  - waybar
  - rofi
  - rofi-calc
  - rofi-emoji
  - dunst
  - grim
  - slurp
  - wl-clipboard  # Fornece wl-copy/wl-paste (clipboard)
  - cliphist
  - playerctl
  - blueman
  - pavucontrol
  - network-manager-applet
  - wlsunset  # Filtro de luz azul
  - zathura
  - zathura-pdf-mupdf
  - swappy

packages_theme:
  - papirus-icon-theme
  - sddm
  - qt5ct
  - qt6ct
  # Fonts
  - ttf-jetbrains-mono-nerd
  - noto-fonts
  - noto-fonts-emoji

packages_terminal:
  - kitty
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - zsh-completions
  - starship
  - eza
  - bat
  - fd
  - ripgrep
  - fzf
  - btop
  - fastfetch
  - tree-sitter-cli
  - jq          # JSON parser (requerido pelos scripts Waybar)
  - pass        # Password store
  - gnupg       # GPG para pass
  - xclip       # Clipboard para pass

packages_dev_tools:
  - neovim
  - lazygit
  - make
  - base-devel
  - docker
  - docker-compose
  - direnv
  - antigravity

packages_distrobox:
  - php
  - php-fpm
  - php-gd
  - php-intl
  - php-redis
  - php-imagick
  - icu
  - composer
  - nodejs
  - npm
  - sqlite
  - mariadb
  - apache
  - php-apache
  - phpmyadmin
  - python
  - python-poetry
  - tk
  - asdf-vm

packages_system:
  - go
  - which
  - curl
  - wget
  - base-devel
  - fakeroot
  - thunar
  - tumbler
  - ffmpegthumbnailer
  - poppler-glib
  - libgsf
  - thunar-volman
  - file-roller
  - gvfs
  - gvfs-smb
  - ntfs-3g
  - dosfstools
  - exfatprogs
  - udiskie
  - unzip
  - zip
  - p7zip
  - unrar
  - less
  - nano
  - xdg-user-dirs
  - mousepad
  - pacman-contrib
  - rsync
  - linux-firmware
  # AMD Graphics
  - mesa
  - vulkan-radeon
  - libva-utils
  - vdpauinfo
  # Programs
  - rofi-rbw
  - rbw
  - firefox
  - mpv
  - inkscape
  - numlockx  # Para ativar NumLock no arranque
  # Kernel Headers
  - linux-lts-headers
  - linux-headers

packages_admin:
  - snapper
  - snap-pac
  - ufw
  - openssh
  - fail2ban  
  - lynis     

# --- Diretórios ---
projects_dir: "{{ target_home }}/Projetos"

# --- Configuração do Sistema ---
keyboard_layout: "pt"
